import fs from "node:fs";
import path from "node:path";
import { sandboxDir } from "./paths";
import {
	enrichMatrixWithMockStates,
	type MatrixCase,
} from "./discover-matrix-doc";
import {
	generateLifecycleSpec,
	generateNavigationSpec,
	generateBridgeSpec,
	generateErrorSpec,
	generatePerformanceSpec,
} from "./discover-hybrid";

export interface AutoGeneratedCase {
	id: string;
	spec: string;
	content: string;
	source: "matrix" | "hybrid" | "chaos";
}

function escapeForDoubleQuotedString(s?: string): string {
	return String(s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function queryLiteral(query?: Record<string, string>): string {
	if (!query || Object.keys(query).length === 0) {
		return "undefined";
	}
	return JSON.stringify(query);
}

/**
 * 根据验收矩阵生成 spec 骨架（v3: mock profile + DeepLink query + 真实 Appium 操作）
 */
export function generateSpecFromMatrix(
	matrixCase: MatrixCase,
	domain: string,
): AutoGeneratedCase {
	const sb = sandboxDir();
	const specPath = path.join(sb, "specs", `${domain}.${matrixCase.caseId}.spec.ts`);

	const op = matrixCase.operation || "";
	const hasOpen = op.includes("打开") || op.includes("进页") || op.includes("进入");
	const hasInput = op.includes("填") || op.includes("输入") || op.includes("修改");
	const hasSubmit = op.includes("提交") || op.includes("确认") || op.includes("点击");
	const hasSelect = op.includes("选") || op.includes("选择");

	const mockProfile = matrixCase.mockProfile || matrixCase.mockStateId || "";
	const mockQuery = matrixCase.mockQuery;
	const isNoClue =
		matrixCase.mockStateId === "NO_CLUE" ||
		/无\s*clueId|缺少\s*clueId|无\s*`?clueId/i.test(matrixCase.preconditions || "");

	const steps: string[] = [];

	steps.push(`// @ts-nocheck`);
	steps.push(`import { browser } from "@wdio/globals";`);
	steps.push(`import { ensureH5NavContext } from "../helpers/ensure-h5-nav-context";`);
	steps.push(`import { switchToWebViewContaining } from "../helpers/webview-context";`);
	steps.push(`import { optimizedLaunch } from "../helpers/deeplink";`);
	steps.push(`import { enableWebMock } from "../orchestration/enable-web-mock";`);
	steps.push(`import { timeouts } from "../config/timeouts";`);
	steps.push("");

	steps.push(`describe("${domain}.${matrixCase.caseId} — ${matrixCase.pageModule}", () => {`);
	steps.push(`  before(async () => {`);
	if (mockProfile) {
		steps.push(`    process.env.E2E_MOCK_PROFILE = ${JSON.stringify(mockProfile)};`);
		steps.push(`    process.env.E2E_ENABLE_WEB_MOCK = "1";`);
		steps.push(`    await enableWebMock(${JSON.stringify(mockProfile)});`);
	}
	if (mockQuery && Object.keys(mockQuery).length > 0) {
		steps.push(`    await optimizedLaunch("${domain}", { query: ${queryLiteral(mockQuery)} });`);
	} else if (isNoClue) {
		steps.push(`    // C01 / NO_CLUE: launch without gate query`);
		steps.push(`    await optimizedLaunch("${domain}");`);
	} else {
		steps.push(`    await switchToWebViewContaining("${domain}", 15000);`);
	}
	steps.push(`    await ensureH5NavContext("${domain}");`);
	steps.push(`  });`);
	steps.push("");

	steps.push(`  it("${escapeForDoubleQuotedString(matrixCase.operation)} → ${escapeForDoubleQuotedString(matrixCase.expectedResult)}", async () => {`);
	steps.push(`    // 前置条件: ${matrixCase.preconditions}`);
	steps.push(`    // 验收约束: ${matrixCase.acceptanceCriteria}`);
	steps.push(`    // 最小验证: ${matrixCase.minimalVerification}`);
	if (matrixCase.mockStateId) {
		steps.push(`    // mockState: ${matrixCase.mockStateId}`);
	}
	steps.push("");

	if (hasOpen && !mockQuery && !isNoClue) {
		steps.push(`    // 打开目标页面`);
		steps.push(`    await browser.url(await browser.getUrl());`);
		steps.push(`    const pageReady = await $("body").isExisting();`);
		steps.push(`    expect(pageReady).toBe(true);`);
	}

	if (hasInput) {
		steps.push(`    // 定位输入框并填入测试数据`);
		steps.push(`    const inputFields = await $$('input:not([type="hidden"]):not([readonly]):not([disabled]), textarea:not([readonly]):not([disabled])');`);
		steps.push(`    for (const el of inputFields) {`);
		steps.push(`      if (await el.isDisplayed() && await el.isEnabled()) {`);
		steps.push(`        const type = await el.getAttribute("type");`);
		steps.push(`        try {`);
		steps.push(`          if (type === "tel" || type === "number") {`);
		steps.push(`            await el.setValue("13800138000");`);
		steps.push(`          } else if (type !== "hidden") {`);
		steps.push(`            await el.setValue("测试数据");`);
		steps.push(`          }`);
		steps.push(`        } catch { /* 元素不可编辑时跳过 */ }`);
		steps.push(`      }`);
		steps.push(`    }`);
	}

	if (hasSelect) {
		steps.push(`    // 选择器交互`);
		steps.push(`    const pickers = await $$('[data-e2e], [data-testid], .picker, .selector, [role="listbox"]');`);
		steps.push(`    if (pickers.length > 0) {`);
		steps.push(`      const first = pickers[0];`);
		steps.push(`      if (await first.isDisplayed()) await first.click();`);
		steps.push(`    }`);
	}

	if (hasSubmit && !isNoClue) {
		steps.push(`    // 定位可交互的提交按钮 (过滤隐藏/disabled 元素)`);
		steps.push(`    const allBts = await $$('button[type="submit"], [data-e2e="submit"], .submit-btn');`);
		steps.push(`    let clicked = false;`);
		steps.push(`    for (const btn of allBts) {`);
		steps.push(`      if (!(await btn.isDisplayed()) || !(await btn.isEnabled())) continue;`);
		steps.push(`      try { await btn.click(); clicked = true; break; } catch { continue; }`);
		steps.push(`    }`);
		steps.push(`    // 回退: CSS 选择器无命中 → 按文本遍历所有 button`);
		steps.push(`    if (!clicked) {`);
		steps.push(`      const visibleBts = await $$('button');`);
		steps.push(`      for (const btn of visibleBts) {`);
		steps.push(`        if (!(await btn.isDisplayed()) || !(await btn.isEnabled())) continue;`);
		steps.push(`        try {`);
		steps.push(`          const t = (await btn.getText()).trim();`);
		steps.push(`          if (t.length > 0) { await btn.click(); clicked = true; break; }`);
		steps.push(`        } catch { continue; }`);
		steps.push(`      }`);
		steps.push(`    }`);
		steps.push(`    if (clicked) {`);
		steps.push(`      await browser.pause(timeouts.submitResponseWait || 2000);`);
		steps.push(`    } else {`);
		steps.push(`      console.warn('[auto-spec] 未找到可交互的提交按钮');`);
		steps.push(`    }`);
	}

	const expected = matrixCase.expectedResult || "";
	const minimal = matrixCase.minimalVerification || "";
	const toastNeedle =
		/缺少车源号/.test(expected + minimal + (matrixCase.acceptanceCriteria || ""))
			? "缺少车源号"
			: /加载失败/.test(expected + minimal)
				? "加载失败"
				: /下架失败/.test(expected + minimal)
					? "下架失败"
					: /提交失败/.test(expected + minimal)
						? "提交失败"
						: "";

	if (isNoClue || toastNeedle === "缺少车源号") {
		steps.push(`    // C01: 无 clueId → Toast「缺少车源号」（仅 execute 轮询，避免 getUrl/browser.url 挂起）`);
		steps.push(`    let saw = false;`);
		steps.push(`    for (let i = 0; i < 8; i++) {`);
		steps.push(`      const hit = await browser.execute(() => {`);
		steps.push(`        var t = document.body ? (document.body.innerText || "") : "";`);
		steps.push(`        var nodes = document.querySelectorAll(".adm-toast, .toast, [role=alert], .van-toast, .adm-toast-mask");`);
		steps.push(`        for (var j = 0; j < nodes.length; j++) {`);
		steps.push(`          if (nodes[j].textContent) t += nodes[j].textContent;`);
		steps.push(`        }`);
		steps.push(`        return t.indexOf("缺少车源号") >= 0;`);
		steps.push(`      }).catch(() => false);`);
		steps.push(`      if (hit) { saw = true; break; }`);
		steps.push(`      await browser.pause(timeouts.PAUSE_SHORT);`);
		steps.push(`    }`);
		steps.push(`    expect(saw).toBe(true);`);
	} else if (expected.includes("Toast") || minimal.includes("Toast") || toastNeedle) {
		const needle = toastNeedle || "";
		steps.push(`    // 验证 Toast 提示出现 (等待最多5秒)`);
		steps.push(`    let toastVisible = false;`);
		steps.push(`    let toastText = "";`);
		steps.push(`    try {`);
		steps.push(`      const toast = await $('.toast, [role="alert"], .van-toast, .t-toast');`);
		steps.push(`      await toast.waitForDisplayed({ timeout: 5000, interval: 500 });`);
		steps.push(`      toastVisible = true;`);
		steps.push(`      toastText = await toast.getText();`);
		steps.push(`    } catch {`);
		steps.push(`      toastText = await $("body").getText();`);
		steps.push(`      toastVisible = toastText.length > 0;`);
		steps.push(`    }`);
		steps.push(`    expect(toastVisible).toBe(true);`);
		if (needle) {
			steps.push(`    expect(toastText).toContain(${JSON.stringify(needle)});`);
		}
	} else if (
		expected.includes("渲染") ||
		minimal.includes("渲染") ||
		expected.includes("展示") ||
		expected.includes("首屏") ||
		expected.includes("车卡")
	) {
		steps.push(`    // 验证页面渲染 / 车卡可见`);
		steps.push(`    const body = await $("body");`);
		steps.push(`    const isRendered = await body.isDisplayed();`);
		steps.push(`    expect(isRendered).toBe(true);`);
		steps.push(`    const bodyText = await body.getText();`);
		steps.push(`    expect(bodyText.length).toBeGreaterThan(10);`);
	} else if (expected.includes("跳转") || expected.includes("导航")) {
		steps.push(`    // 验证页面跳转`);
		steps.push(`    const currentUrl = await browser.getUrl();`);
		steps.push(`    expect(currentUrl).toBeTruthy();`);
	} else {
		steps.push(`    // 通用断言: 页面无崩溃`);
		steps.push(`    const body = await $("body");`);
		steps.push(`    expect(await body.isExisting()).toBe(true);`);
	}

	steps.push(`  });`);
	steps.push(`});`);

	const content = steps.join("\n") + "\n";

	return {
		id: `${domain}.${matrixCase.caseId}`,
		spec: specPath,
		content,
		source: "matrix",
	};
}

/**
 * 根据 Hybrid 场景生成 spec
 */
export function generateHybridSpec(
	hybridId: string,
	domain: string,
): AutoGeneratedCase {
	const sb = sandboxDir();
	const specPath = path.join(sb, "specs", `${hybridId}.spec.ts`);

	let content = "";
	switch (true) {
		case hybridId.includes("lifecycle"):
			content = generateLifecycleSpec(domain);
			break;
		case hybridId.includes("navigation"):
			content = generateNavigationSpec(domain);
			break;
		case hybridId.includes("bridge"):
			content = generateBridgeSpec(domain);
			break;
		case hybridId.includes("error"):
			content = generateErrorSpec(domain);
			break;
		case hybridId.includes("performance"):
			content = generatePerformanceSpec(domain);
			break;
		default:
			content = `// Implement ${hybridId}`;
	}

	return {
		id: hybridId,
		spec: specPath,
		content,
		source: "hybrid",
	};
}

/**
 * 生成混沌测试 spec (v3: 包含真实错误注入逻辑)
 */
export function generateChaosSpec(
	chaosId: string,
	domain: string,
	description?: string,
): AutoGeneratedCase {
	const sb = sandboxDir();
	const specPath = path.join(sb, "chaos", `${chaosId.replace(`${domain}.chaos.`, `${domain}.`)}.chaos.spec.ts`);

	const lines: string[] = [];
	lines.push(`// @ts-nocheck`);
	lines.push(`import { browser } from "@wdio/globals";`);
	lines.push(`import { switchToWebViewContaining } from "../helpers/webview-context";`);
	lines.push(`import { timeouts } from "../config/timeouts";`);
	lines.push("");
	lines.push(`describe("${domain} — 混沌测试: ${description || chaosId}", () => {`);
	lines.push(`  before(async () => {`);
	lines.push(`    await switchToWebViewContaining("${domain}", 15000);`);
	lines.push(`  });`);
	lines.push("");
	lines.push(`  it("${description || chaosId}", async () => {`);

	if (chaosId.includes("network-offline")) {
		lines.push(`    // 模拟网络离线: 页面应展示错误状态而非崩溃`);
		lines.push(`    await browser.execute(() => {`);
		lines.push(`      window.__E2E_MOCK__ = { networkOffline: true };`);
		lines.push(`    });`);
		lines.push(`    const body = await $("body");`);
		lines.push(`    expect(await body.isExisting()).toBe(true);`);
	} else if (chaosId.includes("api-500")) {
		lines.push(`    // 模拟 API 500: 页面应展示错误提示而非白屏`);
		lines.push(`    await browser.execute(() => {`);
		lines.push(`      window.__E2E_MOCK__ = { apiStatus: 500 };`);
		lines.push(`    });`);
		lines.push(`    await browser.pause(timeouts.apiErrorResponseWait || 3000);`);
		lines.push(`    const errHint = await $('.error, .toast, [role="alert"]');`);
		lines.push(`    const hasHint = await errHint.isDisplayed().catch(() => false);`);
		lines.push(`    expect(hasHint).toBe(true);`);
	} else if (chaosId.includes("webview-crash")) {
		lines.push(`    // 模拟 WebView 崩溃恢复`);
		lines.push(`    const contexts = await browser.getContexts();`);
		lines.push(`    expect(contexts.length).toBeGreaterThan(0);`);
	} else if (chaosId.includes("memory-pressure")) {
		lines.push(`    // 内存压力: 分配大量对象后页面仍需响应`);
		lines.push(`    await browser.execute(() => {`);
		lines.push(`      const arr = []; for (let i = 0; i < 10000; i++) arr.push({data: new Array(100)});`);
		lines.push(`    });`);
		lines.push(`    const body = await $("body");`);
		lines.push(`    expect(await body.isExisting()).toBe(true);`);
	} else {
		lines.push(`    // 混沌注入: ${description || chaosId}`);
		lines.push(`    const body = await $("body");`);
		lines.push(`    expect(await body.isExisting()).toBe(true);`);
	}

	lines.push(`  });`);
	lines.push(`});`);

	const content = lines.join("\n") + "\n";

	return {
		id: chaosId,
		spec: specPath,
		content,
		source: "chaos",
	};
}

/**
 * 批量生成 spec
 */
export function autoGenerateCases(
	matrixCases: MatrixCase[],
	domain: string,
): AutoGeneratedCase[] {
	const cases: AutoGeneratedCase[] = [];
	const enriched = enrichMatrixWithMockStates(matrixCases, domain);

	for (const m of enriched) {
		cases.push(generateSpecFromMatrix(m, domain));
	}

	const hybridIds = [
		`${domain}.hybrid.lifecycle`,
		`${domain}.hybrid.navigation`,
		`${domain}.hybrid.bridge`,
		`${domain}.hybrid.error`,
		`${domain}.hybrid.performance`,
	];

	for (const id of hybridIds) {
		cases.push(generateHybridSpec(id, domain));
	}

	const chaosIds = [
		{ id: `${domain}.chaos.network-offline`, description: "网络离线" },
		{ id: `${domain}.chaos.api-500`, description: "API 500 错误" },
		{ id: `${domain}.chaos.slow-3g`, description: "慢速网络" },
		{ id: `${domain}.chaos.empty-list`, description: "空列表" },
		{ id: `${domain}.chaos.stale-session`, description: "过期会话" },
		{ id: `${domain}.chaos.hybrid.webview-crash`, description: "WebView 崩溃恢复" },
		{ id: `${domain}.chaos.hybrid.native-timeout`, description: "Native 操作超时" },
		{ id: `${domain}.chaos.hybrid.bridge-failure`, description: "Bridge 调用失败" },
		{ id: `${domain}.chaos.hybrid.memory-pressure`, description: "内存压力测试" },
		{ id: `${domain}.chaos.hybrid.context-switch-race`, description: "Context 切换竞争" },
	];

	for (const { id, description } of chaosIds) {
		cases.push(generateChaosSpec(id, domain, description));
	}

	return cases;
}

/**
 * 写入 spec 文件。matrix 来源始终覆盖，避免旧 C01-only 骨架残留。
 */
export function writeGeneratedSpecs(cases: AutoGeneratedCase[]): void {
	const sb = sandboxDir();
	const baseDir = path.join(sb, "specs");

	for (const c of cases) {
		const fileName = path.basename(c.spec);
		const fullPath =
			c.source === "chaos"
				? path.join(sb, "chaos", fileName)
				: path.join(baseDir, fileName);
		const dir = path.dirname(fullPath);

		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}

		const existed = fs.existsSync(fullPath);
		const shouldWrite = c.source === "matrix" || !existed;
		if (shouldWrite) {
			fs.writeFileSync(fullPath, c.content, "utf-8");
			console.log(
				`[auto-generate] ${existed ? "Updated" : "Created"}: ${fullPath}`,
			);
		}
	}
}
