import fs from "node:fs";
import path from "node:path";
import { repoRoot, sandboxDir } from "./paths";
import type { MatrixCase } from "./discover-matrix-doc";
import {
	generateLifecycleSpec,
	generateNavigationSpec,
	generateBridgeSpec,
	generateErrorSpec,
	generatePerformanceSpec,
} from "./discover-hybrid";

export interface AutoGeneratedCase {
	id: string;
	spec: string;
	content: string;
	source: "matrix" | "hybrid" | "chaos";
}

/**
 * 根据验收矩阵生成 spec 骨架
 */
export function generateSpecFromMatrix(
	matrixCase: MatrixCase,
	domain: string,
): AutoGeneratedCase {
	const sb = sandboxDir();
	const specPath = path.join(sb, "specs", `${domain}.${matrixCase.caseId}.spec.ts`);

	const content = `import { browser } from "@wdio/globals";

describe("${matrixCase.pageModule}", () => {
  it("${matrixCase.operation} - ${matrixCase.expectedResult}", async () => {
    // 前置条件: ${matrixCase.preconditions}
    // 操作: ${matrixCase.operation}
    // 预期: ${matrixCase.expectedResult}

    // 实现测试逻辑
    // 验收约束: ${matrixCase.acceptanceCriteria}
    // 最小验证: ${matrixCase.minimalVerification}

    expect(true).toBe(true);
  });
});
`;

	return {
		id: `${domain}.${matrixCase.caseId}`,
		spec: specPath,
		content,
		source: "matrix",
	};
}

/**
 * 根据 Hybrid 场景生成 spec
 */
export function generateHybridSpec(
	hybridId: string,
	domain: string,
): AutoGeneratedCase {
	const sb = sandboxDir();
	const specPath = path.join(sb, "specs", `${hybridId}.spec.ts`);

	let content = "";
	switch (true) {
		case hybridId.includes("lifecycle"):
			content = generateLifecycleSpec(domain);
			break;
		case hybridId.includes("navigation"):
			content = generateNavigationSpec(domain);
			break;
		case hybridId.includes("bridge"):
			content = generateBridgeSpec(domain);
			break;
		case hybridId.includes("error"):
			content = generateErrorSpec(domain);
			break;
		case hybridId.includes("performance"):
			content = generatePerformanceSpec(domain);
			break;
		default:
			content = `// Implement ${hybridId}`;
	}

	return {
		id: hybridId,
		spec: specPath,
		content,
		source: "hybrid",
	};
}

/**
 * 生成混沌测试 spec
 */
export function generateChaosSpec(
	chaosId: string,
	domain: string,
	description?: string,
): AutoGeneratedCase {
	// 修复：生成的文件路径应与注册路径一致
	// 注册路径已在 sandbox/chaos/ 下
	// 实际路径在 sandbox/chaos/ 下
	const sb = sandboxDir();
	const specPath = path.join(sb, "chaos", `${chaosId.replace(`${domain}.chaos.`, `${domain}.`)}.chaos.spec.ts`);

	const content = `import { browser } from "@wdio/globals";

describe("${domain} - 混沌测试", () => {
  it("${description || chaosId}", async () => {
    // 实现混沌测试逻辑
    // 场景: ${chaosId}
    // 描述: ${description || "混沌测试"}

    // 1. 模拟异常条件
    // 2. 验证系统行为
    // 3. 验证恢复能力

    expect(true).toBe(true);
  });
});
`;

	return {
		id: chaosId,
		spec: specPath,
		content,
		source: "chaos",
	};
}

/**
 * 批量生成 spec
 */
export function autoGenerateCases(
	matrixCases: MatrixCase[],
	domain: string,
): AutoGeneratedCase[] {
	const cases: AutoGeneratedCase[] = [];

	// 从验收矩阵生成
	for (const m of matrixCases) {
		cases.push(generateSpecFromMatrix(m, domain));
	}

	// 生成 Hybrid 测试用例
	const hybridIds = [
		`${domain}.hybrid.lifecycle`,
		`${domain}.hybrid.navigation`,
		`${domain}.hybrid.bridge`,
		`${domain}.hybrid.error`,
		`${domain}.hybrid.performance`,
	];

	for (const id of hybridIds) {
		cases.push(generateHybridSpec(id, domain));
	}

	// 生成混沌测试用例
	const chaosIds = [
		{ id: `${domain}.chaos.network-offline`, description: "网络离线" },
		{ id: `${domain}.chaos.api-500`, description: "API 500 错误" },
		{ id: `${domain}.chaos.slow-3g`, description: "慢速网络" },
		{ id: `${domain}.chaos.empty-list`, description: "空列表" },
		{ id: `${domain}.chaos.stale-session`, description: "过期会话" },
		{ id: `${domain}.chaos.hybrid.webview-crash`, description: "WebView 崩溃恢复" },
		{ id: `${domain}.chaos.hybrid.native-timeout`, description: "Native 操作超时" },
		{ id: `${domain}.chaos.hybrid.bridge-failure`, description: "Bridge 调用失败" },
		{ id: `${domain}.chaos.hybrid.memory-pressure`, description: "内存压力测试" },
		{ id: `${domain}.chaos.hybrid.context-switch-race`, description: "Context 切换竞争" },
	];

	for (const { id, description } of chaosIds) {
		cases.push(generateChaosSpec(id, domain, description));
	}

	return cases;
}

/**
 * 写入 spec 文件
 */
export function writeGeneratedSpecs(cases: AutoGeneratedCase[]): void {
	// v2: 写入沙箱 (不污染项目)
	const sb = sandboxDir();
	const baseDir = path.join(sb, "specs");

	for (const c of cases) {
		const fileName = path.basename(c.spec);
		const fullPath = path.join(baseDir, fileName);
		const dir = path.dirname(fullPath);

		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}

		if (!fs.existsSync(fullPath)) {
			fs.writeFileSync(fullPath, c.content, "utf-8");
			console.log(`[auto-generate] Created: ${c.spec}`);
		}
	}
}
